### PR TITLE
symlinks for 2.068.0

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Now also with links for 2.068.1-b2, see #6.

**Comment by braddr** [comment]
This repo should be forked over into the D-Programming-Language org so that others w/in the org can approve changes.

**Comment by MartinNowak** [comment]
> This repo should be forked over into the D-Programming-Language org so that others w/in the org can approve changes.

Yes, good point, but only you can do it @braddr https://github.com/braddr/downloads.dlang.org/settings ;).

**Comment by braddr** [comment]
Not true.. only I can re-assign an existing repo in another account, but anyone part of the org can fork a repository into the org.  Just click on the fork button and a select org ui pops up.

**Comment by MartinNowak** [comment]
> but anyone part of the org can fork a repository into the org

I don't have the rights to fork the repo. Please reassign it to DPL, it's also cleaner b/c github then knows it's the main repo.

**Pull request merged**
