### PR TITLE
use dlang.org to build downloads.dlang.org pages

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by braddr** [comment]
I don't really want that code to depend on having a dmd in the path, nor do I want it to depend on having dlang.org (and that it be updated correctly).  I also don't like the hardcoded copy of the html being in the code, but I prefer that over the other two dependecies.

**Comment by MartinNowak** [comment]
But you can't expect anyone to keep that up to date with dlang.org.
What's the problem with dmd and dlang.org? It's a requirement for anything else already.

**Comment by MartinNowak** [comment]
I made DMD and DLANG_ORG configurable through the environment.

**Comment by andralex** [comment]
@braddr there are a number of issues with downloads.dlang.org:
- It doesn't render properly
- The links are too long: http://downloads.dlang.org/releases/2.x/2.067.0/ should really be http://downloads.dlang.org/2.067.0/
- The nicest link, http://downloads.dlang.org, leads to a uninformative page

Could you please look into fixing these? Thanks!

**Pull request merged**
